version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    expose:
      - 5000

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - 80:80
    depends_on:
      - web

  db:
    environment:
      POSTGRES_ROOT_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    image: postgres:${POSTGRES_VERSION}
    networks:
      - default
    ports:
      - 5405:5432
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
