version: '3'
services:
  web:
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - db
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=5000'

    command: flask run --host=0.0.0.0 --port=5000
#    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - 80:80
    depends_on:
      - web

  db:
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: C@Gh!bL
      POSTGRES_DB: pos_db
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080