version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    environment:
      - FLASK_APP=run.py
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80

  db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
